/* Copyright Statement:
*
* This software/firmware and related documentation ("MediaTek Software") are
* protected under relevant copyright laws. The information contained herein
* is confidential and proprietary to MediaTek Inc. and/or its licensors.
* Without the prior written permission of MediaTek inc. and/or its licensors,
* any reproduction, modification, use or disclosure of MediaTek Software,
* and information contained herein, in whole or in part, shall be strictly prohibited.
*/
/* MediaTek Inc. (C) 2015. All rights reserved.
*
* BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
* THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
* RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
* AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
* NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
* SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
* SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
* THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
* THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
* CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
* SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
* STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
* CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
* AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
* OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
* MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*/
#ifndef _LCM_DEFINE_H
#define _LCM_DEFINE_H

#if defined(MTK_LCM_DEVICE_TREE_SUPPORT)
/* LCM_FUNC */
#define LCM_FUNC_GPIO   1
#define LCM_FUNC_I2C    2
#define LCM_FUNC_UTIL   3
#define LCM_FUNC_CMD    4

/* LCM_GPIO_TYPE */
#define LCM_GPIO_MODE   1
#define LCM_GPIO_DIR    2
#define LCM_GPIO_OUT    3

/* LCM_GPIO_MODE_DATA */
#define LCM_GPIO_MODE_00    0
#define LCM_GPIO_MODE_01    1
#define LCM_GPIO_MODE_02    2
#define LCM_GPIO_MODE_03    3
#define LCM_GPIO_MODE_04    4
#define LCM_GPIO_MODE_05    5
#define LCM_GPIO_MODE_06    6
#define LCM_GPIO_MODE_07    7
#define MAX_LCM_GPIO_MODE    8

/* LCM_GPIO_DIR_DATA */
#define LCM_GPIO_DIR_IN 0
#define LCM_GPIO_DIR_OUT    1

/* LCM_GPIO_OUT_DATA */
#define LCM_GPIO_OUT_ZERO   0
#define LCM_GPIO_OUT_ONE    1

/* LCM_I2C_TYPE */
#define LCM_I2C_WRITE   1

/* LCM_UTIL_TYPE */
#define LCM_UTIL_RESET  1
#define LCM_UTIL_MDELAY 2
#define LCM_UTIL_UDELAY 3
#define LCM_UTIL_WRITE_CMD_V1   4
#define LCM_UTIL_WRITE_CMD_V2   5
#define LCM_UTIL_READ_CMD_V1    6
#define LCM_UTIL_READ_CMD_V2    7
#define LCM_UTIL_WRITE_CMD_V21	8
#define LCM_UTIL_WRITE_CMD_V22	9
#define LCM_UTIL_WRITE_CMD_V23	10

/* LCM_UTIL_RESET_DATA */
#define LCM_UTIL_RESET_LOW  0
#define LCM_UTIL_RESET_HIGH 1
#endif

#endif              /* _LCM_DEFINE_H */
